version: '3.8'  

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "4200:80"  
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "8080:80"  
    environment:
      ASPNETCORE_ENVIRONMENT: Development 
