version: '3.8'  # Specify the version of Docker Compose

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile  # Adjust based on your frontend Dockerfile
    ports:
      - "4200:80"  # Map host port 4200 to container port 80 (Angular app)
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile  # Adjust based on your backend Dockerfile
    ports:
      - "8080:80"  # Map host port 8080 to container port 80 (API)
    environment:
      ASPNETCORE_ENVIRONMENT: Development  # Adjust based on your environment
